import { Link } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import AppShell from '../components/layout/AppShell.jsx';
import useLanguage from '../hooks/useLanguage.js';
import { useAdminDashboardStatistics } from '../hooks/useAdminDashboard.js';

const COLORS = ['#2563eb', '#0891b2', '#16a34a', '#d97706', '#9333ea', '#dc2626', '#4f46e5', '#0f766e'];
const errorMessage = (error, fallback) => error?.response?.data?.message || fallback;

export default function AdminDashboard() {
  const { t, locale } = useLanguage();
  const { data, isLoading, isError, error, refetch, isFetching } = useAdminDashboardStatistics();
  if (isLoading) return <AppShell><LoadingState /></AppShell>;
  if (isError) return <AppShell><ErrorState message={errorMessage(error, t('adminDashboardLoadError'))} onRetry={refetch} /></AppShell>;
  const metrics = data?.metrics || {};
  const charts = data?.charts || {};
  const pending = data?.pending || {};
  const feedback = data?.feedback || {};
  return <AppShell><div className="flex flex-col gap-3 mb-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-gray-500">{t('dashboard')} / {t('adminDashboard')}</p><h1 className="mt-1 text-2xl font-bold text-gray-800">{t('adminDashboardTitle')}</h1><p className="mt-1 text-gray-500">{t('adminDashboardSubtitle')}</p></div><div className="flex items-center gap-3"><span className="text-xs text-gray-400">{data?.generatedAt ? t('dashboardUpdated', { date: new Date(data.generatedAt).toLocaleTimeString(locale) }) : ''}</span>{isFetching && <span className="text-xs text-primary-600">{t('refreshing')}</span>}</div></div><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label={t('totalEmployees')} value={metrics.totalEmployees} to="/employees" /><StatCard label={t('activeEmployees')} value={metrics.activeEmployees} to="/employees" /><StatCard label={t('activeInterns')} value={metrics.activeInterns} to="/interns?status=active" /><StatCard label={t('upcomingInterns')} value={metrics.upcomingInterns} to="/interns?status=upcoming" /><StatCard label={t('departments')} value={metrics.departments} to="/departments" /><StatCard label={t('liveAnnouncements')} value={metrics.liveAnnouncements} to="/announcements" /><StatCard label={t('knowledgeArticles')} value={metrics.knowledgeArticles} to="/it-help" /><StatCard label={t('pendingFeedback')} value={metrics.pendingFeedback} to="/admin/feedback" tone="warning" /><StatCard label={t('feedbackTotal')} value={metrics.feedbackTotal} to="/admin/feedback" /><StatCard label={t('feedbackResolved')} value={metrics.feedbackResolved} to="/admin/feedback?status=resolved" /><StatCard label={t('feedbackAverageRating')} value={metrics.feedbackAverageRating ?? '—'} to="/admin/feedback" /></section><section className="mt-6 grid gap-5 lg:grid-cols-2"><ChartCard title={t('internsByUniversity')}><DistributionChart data={charts.internsByUniversity} /></ChartCard><ChartCard title={t('employeesByDepartment')}><DepartmentChart data={charts.employeesByDepartment} /></ChartCard><ChartCard title={t('internsByDepartment')}><DepartmentChart data={charts.internsByDepartment} /></ChartCard><ChartCard title={t('internsByBatch')}><DepartmentChart data={charts.internsByBatch} /></ChartCard><ChartCard title={t('feedbackByCategory')}><DepartmentChart data={feedback.byCategory} /></ChartCard><ChartCard title={t('feedbackByStatus')}><DepartmentChart data={feedback.byStatus} /></ChartCard></section><section className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><ActivityFeed items={data?.recentActivity || []} /><PendingItems pending={pending} /></section><QuickActions /></AppShell>;
}

function StatCard({ label, value = 0, to, tone = 'default' }) { const display = typeof value === 'number' ? value.toLocaleString() : value; return <Link to={to} className={`block rounded-xl border p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${tone === 'warning' ? 'border-amber-200 bg-amber-50' : 'border-gray-200 bg-white'}`}><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-3xl font-bold text-gray-800">{display}</p></Link>; }
function ChartCard({ title, children }) { return <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-gray-800">{title}</h2><div className="mt-4 h-64">{children}</div></section>; }
function DistributionChart({ data = [] }) { const { t } = useLanguage(); if (!data.length) return <EmptyChart />; return <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="count" nameKey="label" cx="50%" cy="45%" outerRadius={82} label={({ label, percent }) => `${label} ${(percent * 100).toFixed(0)}%`}>{data.map((entry, index) => <Cell key={entry.label} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip /><Legend /></PieChart></ResponsiveContainer>; }
function DepartmentChart({ data = [] }) { if (!data.length) return <EmptyChart />; return <ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 8, right: 12, bottom: 28, left: 0 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" angle={-25} textAnchor="end" interval={0} height={60} tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="count" fill="#2563eb" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer>; }
function EmptyChart() { const { t } = useLanguage(); return <div className="h-full flex items-center justify-center text-sm text-gray-400">{t('noChartData')}</div>; }
function ActivityFeed({ items }) { const { t } = useLanguage(); return <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-gray-800">{t('recentActivity')}</h2>{items.length === 0 ? <p className="mt-4 text-sm text-gray-500">{t('noRecentActivity')}</p> : <div className="mt-3 divide-y divide-gray-100">{items.map((item) => <div key={item.id} className="flex items-start justify-between gap-3 py-3 first:pt-0 last:pb-0"><div><p className="text-sm text-gray-700">{t('activityItem', { action: item.action, entity: item.entity, actor: item.actor })}</p><p className="mt-1 text-xs text-gray-400">{item.createdAt ? new Date(item.createdAt).toLocaleString() : ''}</p></div></div>)}</div>}</section>; }
function PendingItems({ pending }) { const { t } = useLanguage(); const items = [{ label: t('pendingAnnouncements'), value: pending.announcements, to: '/announcements' }, { label: t('pendingPolicies'), value: pending.policies, to: '/policies' }, { label: t('pendingFaqs'), value: pending.faqs, to: '/faq' }, { label: t('pendingKnowledgeArticles'), value: pending.knowledgeArticles, to: '/it-help' }, { label: t('pendingFeedback'), value: pending.feedback, to: '/admin/feedback' }]; return <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold text-gray-800">{t('pendingItems')}</h2><span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-800">{pending.total || 0}</span></div><div className="mt-3 divide-y divide-gray-100">{items.map((item) => <Link key={item.label} to={item.to} className="flex items-center justify-between py-3 text-sm hover:text-primary-600"><span>{item.label}</span><span className="font-semibold">{item.value || 0}</span></Link>)}</div></section>; }
function QuickActions() { const { t } = useLanguage(); const actions = [{ label: t('addEmployee'), to: '/employees?create=1' }, { label: t('addIntern'), to: '/interns?create=1' }, { label: t('addDepartment'), to: '/departments?create=1' }, { label: t('addAnnouncement'), to: '/announcements?create=1' }, { label: t('addItHelp'), to: '/it-help?create=1' }]; return <section className="mt-6 rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-gray-800">{t('quickActions')}</h2><div className="mt-3 flex flex-wrap gap-2">{actions.map((action) => <Link key={action.to} to={action.to} className="rounded-md bg-primary-600 px-3 py-2 text-sm font-medium text-white hover:bg-primary-700">{action.label}</Link>)}</div></section>; }
function LoadingState() { const { t } = useLanguage(); return <div className="space-y-5"><div><div className="h-7 w-64 animate-pulse rounded bg-gray-200" /><div className="mt-2 h-4 w-96 max-w-full animate-pulse rounded bg-gray-100" /></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 8 }, (_, index) => <div key={index} className="h-28 animate-pulse rounded-xl bg-white border border-gray-200" />)}</div><p className="text-center text-sm text-gray-500">{t('loadingAdminDashboard')}</p></div>; }
function ErrorState({ message, onRetry }) { const { t } = useLanguage(); return <div className="rounded-xl border border-red-200 bg-red-50 p-8 text-center"><p className="text-red-700">{message}</p><button type="button" onClick={() => onRetry()} className="mt-4 rounded-md bg-red-600 px-4 py-2 text-sm font-medium text-white">{t('tryAgain')}</button></div>; }
