import { useState } from 'react';
import { Link } from 'react-router-dom';
import AppShell from '../components/layout/AppShell.jsx';
import Modal from '../components/common/Modal.jsx';
import ConfirmDialog from '../components/common/ConfirmDialog.jsx';
import Pagination from '../components/common/Pagination.jsx';
import useAuth from '../hooks/useAuth.js';
import useLanguage from '../hooks/useLanguage.js';
import { useAdminUsers, useBulkDeactivateAdminUsers, useCreateAdminUser, useResetAdminUserPassword, useUpdateAdminUser } from '../hooks/useAdminUsers.js';
import { ROLE_LABELS } from '../utils/permissions.js';

const ROLES = ['super_admin', 'admin', 'editor', 'staff', 'intern'];

export default function AdminUsers() {
  const { user: currentUser, hasRole } = useAuth();
  const { t } = useLanguage();
  const canChangeRoles = hasRole('super_admin');
  const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [active, setActive] = useState(''); const [page, setPage] = useState(1); const [selected, setSelected] = useState([]);
  const [form, setForm] = useState(null); const [resetTarget, setResetTarget] = useState(null); const [bulkOpen, setBulkOpen] = useState(false); const [credential, setCredential] = useState(''); const [error, setError] = useState(''); const [fieldErrors, setFieldErrors] = useState({});
  const params = { ...(search.trim() && { search: search.trim() }), ...(role && { role }), ...(active !== '' && { active }), page, limit: 15 };
  const usersQuery = useAdminUsers(params); const create = useCreateAdminUser(); const update = useUpdateAdminUser(); const reset = useResetAdminUserPassword(); const bulk = useBulkDeactivateAdminUsers();
  const users = usersQuery.data?.data || [];
  const usersErrorMessage = usersQuery.error?.response?.data?.message || usersQuery.error?.message || t('unableLoad');
  const refreshFilters = (setter) => (event) => { setter(event.target.value); setPage(1); setSelected([]); };
  const toggleSelected = (id) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const buildPayload = (values) => ({ username: (values.username || '').trim().toLowerCase(), email: (values.email || '').trim(), role: values.role, ...(values.password ? { password: values.password } : {}) });
  const save = async (event) => { event.preventDefault(); setError(''); setFieldErrors({}); try { const payload = buildPayload(form.values); const result = form.mode === 'create' ? await create.mutateAsync(payload) : await update.mutateAsync({ id: form.user._id, payload }); if (result.data?.temporaryPassword) setCredential(result.data.temporaryPassword); setForm(null); } catch (requestError) { const response = requestError.response?.data; setFieldErrors(response?.errors && typeof response.errors === 'object' ? response.errors : {}); setError(response?.message || 'Unable to save user.'); } };
  const doReset = async () => { setError(''); try { const result = await reset.mutateAsync({ id: resetTarget._id }); setCredential(result.data.temporaryPassword); setResetTarget(null); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to reset password.'); } };
  const doBulkDeactivate = async () => { setError(''); try { await bulk.mutateAsync(selected); setSelected([]); setBulkOpen(false); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to deactivate selected users.'); } };
  const toggleActive = async (item) => { setError(''); try { await update.mutateAsync({ id: item._id, payload: { isActive: !item.isActive } }); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to change account status.'); } };

  return <AppShell rightContent={<Link to="/dashboard" className="text-sm text-gray-500 hover:text-gray-700">{t('backDashboard')}</Link>}><main>
    <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3 mb-6"><div><h1 className="text-2xl font-bold text-gray-800">User Management</h1><p className="text-sm text-gray-500 mt-1">Manage accounts, access status, and administrative actions.</p></div><div className="flex gap-2"><button onClick={() => { setError(''); setFieldErrors({}); setForm({ mode: 'create', values: { username: '', email: '', password: '', role: 'staff' } }); }} className="rounded-md bg-primary-600 px-4 py-2 text-sm font-medium text-white hover:bg-primary-700">Add user</button>{hasRole('super_admin') && <Link to="/admin/audit-logs" className="rounded-md border border-gray-300 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">Audit log</Link>}</div></div>
    {error && <p className="mb-4 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}
    <div className="grid gap-3 rounded-xl border border-gray-200 bg-white p-4 sm:grid-cols-3"><input value={search} onChange={refreshFilters(setSearch)} placeholder="Search username or email" className="px-3 py-2 border border-gray-300 rounded-md" /><select value={role} onChange={refreshFilters(setRole)} className="px-3 py-2 border border-gray-300 rounded-md"><option value="">All roles</option>{ROLES.map((item) => <option key={item} value={item}>{ROLE_LABELS[item]}</option>)}</select><select value={active} onChange={refreshFilters(setActive)} className="px-3 py-2 border border-gray-300 rounded-md"><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div>
    <div className="mt-4 flex items-center justify-between gap-3"><p className="text-sm text-gray-500">{usersQuery.data?.pagination?.total || 0} accounts</p>{selected.length > 0 && <button onClick={() => setBulkOpen(true)} className="rounded-md bg-red-600 px-3 py-2 text-sm font-medium text-white hover:bg-red-700">Deactivate selected ({selected.length})</button>}</div>
    <div className="mt-3 overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-4 py-3"></th><th className="px-4 py-3">Account</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Last login</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{usersQuery.isLoading ? <tr><td colSpan="6" className="px-4 py-8 text-center text-gray-500">Loading users...</td></tr> : usersQuery.isError ? <tr><td colSpan="6" className="px-4 py-8"><div className="text-center" role="alert"><p className="font-medium text-red-700">{t('unableLoad')}</p><p className="mt-1 text-sm text-red-600">{usersErrorMessage}</p><button type="button" onClick={() => usersQuery.refetch()} className="mt-4 rounded-md bg-primary-600 px-4 py-2 text-sm font-medium text-white hover:bg-primary-700">{t('tryAgain')}</button></div></td></tr> : users.length === 0 ? <tr><td colSpan="6" className="px-4 py-8 text-center text-gray-500">No users match these filters.</td></tr> : users.map((item) => <tr key={item._id} className="hover:bg-gray-50"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(item._id)} disabled={!item.isActive || item._id === currentUser?._id} onChange={() => toggleSelected(item._id)} aria-label={`Select ${item.username}`} /></td><td className="px-4 py-3"><p className="font-medium text-gray-800">{item.username}</p><p className="text-xs text-gray-500">{item.email}</p></td><td className="px-4 py-3">{canChangeRoles ? <select value={item.role} onChange={(event) => update.mutate({ id: item._id, payload: { role: event.target.value } })} disabled={item._id === currentUser?._id || update.isPending} className="border border-gray-300 rounded px-2 py-1 text-xs"><option value={item.role}>{ROLE_LABELS[item.role]}</option>{ROLES.filter((candidate) => candidate !== item.role).map((candidate) => <option key={candidate} value={candidate}>{ROLE_LABELS[candidate]}</option>)}</select> : <span>{ROLE_LABELS[item.role] || item.role}</span>}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-medium ${item.isActive ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'}`}>{item.isActive ? 'Active' : 'Inactive'}</span></td><td className="px-4 py-3 text-gray-500">{item.lastLoginAt ? new Date(item.lastLoginAt).toLocaleString() : 'Never'}</td><td className="px-4 py-3 text-right whitespace-nowrap"><button onClick={() => toggleActive(item)} disabled={item._id === currentUser?._id || update.isPending} className="mr-3 text-primary-600 hover:underline disabled:opacity-50">{item.isActive ? 'Deactivate' : 'Activate'}</button><button onClick={() => setResetTarget(item)} className="text-amber-600 hover:underline">Reset password</button></td></tr>)}</tbody></table></div>
    {usersQuery.data?.pagination && <Pagination {...usersQuery.data.pagination} onPageChange={setPage} disabled={usersQuery.isFetching} />}
    <Modal open={!!form} onClose={() => { setForm(null); setFieldErrors({}); }} title={form?.mode === 'create' ? 'Create user' : 'Edit user'}><form onSubmit={save} className="space-y-4" noValidate>{error && <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700" role="alert">{error}</p>}<Field label="Username" error={fieldErrors.username}><input required value={form?.values.username || ''} onChange={(event) => setForm({ ...form, values: { ...form.values, username: event.target.value } })} className="field block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-800 shadow-sm placeholder:text-gray-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-100 disabled:bg-gray-100 disabled:text-gray-500" /></Field><Field label="Email" error={fieldErrors.email}><input required type="email" value={form?.values.email || ''} onChange={(event) => setForm({ ...form, values: { ...form.values, email: event.target.value } })} className="field block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-800 shadow-sm placeholder:text-gray-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-100 disabled:bg-gray-100 disabled:text-gray-500" /></Field><Field label="Role" error={fieldErrors.role}><select value={form?.values.role || 'staff'} onChange={(event) => setForm({ ...form, values: { ...form.values, role: event.target.value } })} className="field block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-800 shadow-sm placeholder:text-gray-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-100 disabled:bg-gray-100 disabled:text-gray-500">{ROLES.filter((item) => canChangeRoles || item !== 'super_admin').map((item) => <option key={item} value={item}>{ROLE_LABELS[item]}</option>)}</select></Field><Field label="Password (optional; a temporary password is generated if blank)" error={fieldErrors.password}><input type="password" value={form?.values.password || ''} onChange={(event) => setForm({ ...form, values: { ...form.values, password: event.target.value } })} className="field block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-800 shadow-sm placeholder:text-gray-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-100 disabled:bg-gray-100 disabled:text-gray-500" /></Field><div className="flex justify-end gap-3"><button type="button" onClick={() => { setForm(null); setFieldErrors({}); }} className="rounded-md border border-gray-300 px-4 py-2 text-sm">Cancel</button><button disabled={create.isPending || update.isPending} className="rounded-md bg-primary-600 px-4 py-2 text-sm font-medium text-white">{create.isPending || update.isPending ? 'Saving...' : 'Save user'}</button></div></form></Modal>
    <ConfirmDialog open={!!resetTarget} onClose={() => setResetTarget(null)} onConfirm={doReset} title="Reset password" message={resetTarget ? `Generate a new temporary password for ${resetTarget.username}?` : ''} confirmLabel="Reset password" loading={reset.isPending} danger={false} />
    <ConfirmDialog open={bulkOpen} onClose={() => setBulkOpen(false)} onConfirm={doBulkDeactivate} title="Deactivate selected users" message={`Deactivate ${selected.length} selected active account(s)?`} confirmLabel="Deactivate" loading={bulk.isPending} />
    <Modal open={!!credential} onClose={() => setCredential('')} title="Temporary password"><p className="text-sm text-gray-600">Copy this password now. It is shown only once and the user must change it after signing in.</p><code className="mt-4 block rounded-md bg-gray-100 p-3 text-center font-mono text-lg select-all">{credential}</code><div className="mt-5 flex justify-end"><button onClick={() => setCredential('')} className="rounded-md bg-primary-600 px-4 py-2 text-sm text-white">Close</button></div></Modal>
  </main></AppShell>;
}

function Field({ label, error, children }) {
  return <label className="block text-sm font-medium text-gray-700">{label}<span className="mt-1 block">{children}</span>{error && <span className="mt-1 block text-sm font-normal text-red-600">{error}</span>}</label>;
}
