import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';

import AppShell from '../components/layout/AppShell.jsx';
import useAuth from '../hooks/useAuth.js';
import useLanguage from '../hooks/useLanguage.js';
import { useEmployees, useDepartments, useCreateEmployee, useUpdateEmployee, useDeleteEmployee } from '../hooks/useEmployees.js';
import DataTable from '../components/common/DataTable.jsx';
import SearchBar from '../components/common/SearchBar.jsx';
import Pagination from '../components/common/Pagination.jsx';
import Modal from '../components/common/Modal.jsx';
import ConfirmDialog from '../components/common/ConfirmDialog.jsx';
import EmployeeForm from '../components/employees/EmployeeForm.jsx';
import { ImageWithFallback } from '../components/common/ImageUpload.jsx';

const PAGE_SIZE = 10;
export default function Employees() {
  const { hasPermission } = useAuth(); const { t } = useLanguage(); const canManage = hasPermission('employees:manage'); const [searchParams] = useSearchParams();
  const [search, setSearch] = useState(''); const [department, setDepartment] = useState(() => searchParams.get('department') || ''); const [page, setPage] = useState(1);
  const { data, isLoading, isError, error, isFetching, refetch } = useEmployees({ search, department, page, limit: PAGE_SIZE }); const { data: departments = [] } = useDepartments(); const createMut = useCreateEmployee(); const updateMut = useUpdateEmployee(); const deleteMut = useDeleteEmployee();
  const [formOpen, setFormOpen] = useState(() => searchParams.get('create') === '1'); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const [serverErrors, setServerErrors] = useState({}); const [formError, setFormError] = useState(''); const [uploadProgress, setUploadProgress] = useState(0);
  const reset = (setter) => (value) => { setter(value); setPage(1); }; const openCreate = () => { setEditing(null); setServerErrors({}); setFormError(''); setFormOpen(true); }; const openEdit = (item) => { setEditing(item); setServerErrors({}); setFormError(''); setFormOpen(true); };
  const submit = async (payload, file) => { setServerErrors({}); setFormError(''); setUploadProgress(0); const onUploadProgress = (event) => { if (event.total) setUploadProgress(Math.round((event.loaded / event.total) * 100)); }; try { if (editing) await updateMut.mutateAsync({ id: editing._id, payload, file, onUploadProgress }); else await createMut.mutateAsync({ payload, file, onUploadProgress }); setFormOpen(false); } catch (requestError) { const response = requestError.response?.data; if (response?.errors) setServerErrors(response.errors); setFormError(response?.message || t('saveEmployeeError')); } };
  const remove = async () => { try { await deleteMut.mutateAsync(deleting._id); setDeleting(null); } catch {} };
  const columns = [{ key: 'employeeCode', header: t('code') }, { key: 'name', header: t('name'), render: (item) => <div className="flex items-center gap-2"><ImageWithFallback src={item.profileImage} alt={`${item.firstName} ${item.lastName}`} className="w-8 h-8 rounded-full object-cover" fallback={`${item.firstName?.[0] || ''}${item.lastName?.[0] || ''}`} /><div><span className="font-medium text-gray-800">{item.firstName} {item.lastName}</span>{item.nickname && <span className="text-gray-400"> ({item.nickname})</span>}</div></div> }, { key: 'position', header: t('position') }, { key: 'department', header: t('departments'), render: (item) => item.departmentId?.name || '-' }, { key: 'status', header: t('status'), render: (item) => <div className="flex gap-1">{!item.isActive && <Badge tone="gray">{t('inactive')}</Badge>}{!item.isPublished && <Badge tone="amber">{t('hidden')}</Badge>}{item.isActive && item.isPublished && <Badge tone="green">{t('active')}</Badge>}</div> }];
  if (canManage) columns.push({ key: 'actions', header: '', className: 'text-right', render: (item) => <div className="flex justify-end gap-2"><button onClick={() => openEdit(item)} className="text-primary-600 hover:underline text-sm">{t('edit')}</button><button onClick={() => setDeleting(item)} className="text-red-600 hover:underline text-sm">{t('delete')}</button></div> });
  return <AppShell><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8"><div className="flex flex-col sm:flex-row sm:items-center gap-3 mb-4"><SearchBar value={search} onSearch={reset(setSearch)} placeholder={t('searchEmployees')} /><select value={department} onChange={(event) => reset(setDepartment)(event.target.value)} className="px-3 py-2 border border-gray-300 rounded-md"><option value="">{t('allDepartments')}</option>{departments.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select>{canManage && <button onClick={openCreate} className="sm:ml-auto bg-primary-600 text-white px-4 py-2 rounded-md text-sm font-medium">{t('addEmployee')}</button>}</div><DataTable columns={columns} rows={data?.data} loading={isLoading} error={isError ? error : null} onRetry={refetch} emptyTitle={t('noEmployees')} emptyMessage={search || department ? t('adjustFilters') : t('addFirstEmployee')} />{data?.pagination && <Pagination {...data.pagination} onPageChange={setPage} disabled={isFetching} />}<Modal open={formOpen} onClose={() => setFormOpen(false)} title={editing ? t('editEmployee') : t('addEmployeeTitle')} size="lg">{formError && <p className="mb-4 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md px-3 py-2">{formError}</p>}<EmployeeForm initial={editing} departments={departments} onSubmit={submit} onCancel={() => setFormOpen(false)} submitting={createMut.isPending || updateMut.isPending} uploadProgress={uploadProgress} serverErrors={serverErrors} /></Modal><ConfirmDialog open={!!deleting} onClose={() => setDeleting(null)} onConfirm={remove} title={t('deleteEmployee')} message={deleting ? t('deleteConfirm', { name: `${deleting.firstName} ${deleting.lastName}` }) : ''} confirmLabel={t('delete')} loading={deleteMut.isPending} /></div></AppShell>;
}
function Badge({ tone, children }) { const tones = { green: 'bg-green-100 text-green-700', amber: 'bg-amber-100 text-amber-700', gray: 'bg-gray-100 text-gray-600' }; return <span className={`px-2 py-0.5 rounded text-xs font-medium ${tones[tone]}`}>{children}</span>; }
