import { useEffect, useState } from 'react';
import useAuth from '../hooks/useAuth.js';
import useLanguage from '../hooks/useLanguage.js';
import { useCreateKnowledgeArticle, useDeleteKnowledgeArticle, useKnowledgeArticles, useKnowledgeCategories, useUpdateKnowledgeArticle } from '../hooks/useKnowledge.js';
import AppShell from '../components/layout/AppShell.jsx';
import Modal from '../components/common/Modal.jsx';
import ConfirmDialog from '../components/common/ConfirmDialog.jsx';
import ContentBadge from '../components/content/ContentBadge.jsx';
import { RichTextEditor, RichTextRenderer } from '../components/content/RichText.jsx';

const DEFAULT_SECTIONS = ['first_day', 'first_week', 'before_leaving'];
const EMPTY_ARTICLE = { title: '', slug: '', subcategory: 'first_day', summary: '', content: '', coverImage: '', tags: '', targetRoles: [], sortOrder: 0, status: 'draft' };
const errorMessage = (error, fallback) => error?.response?.data?.message || fallback;

export default function GettingStarted() {
  const { hasPermission } = useAuth(); const { t, label } = useLanguage(); const canManage = hasPermission('knowledge:manage');
  const [section, setSection] = useState('first_day'); const [status, setStatus] = useState(''); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const [formError, setFormError] = useState('');
  const { data, isLoading, isError, error } = useKnowledgeArticles({ category: 'getting_started', limit: 100, ...(canManage && status ? { status } : {}) });
  const { data: catalog } = useKnowledgeCategories(); const createMutation = useCreateKnowledgeArticle(); const updateMutation = useUpdateKnowledgeArticle(); const deleteMutation = useDeleteKnowledgeArticle();
  const sections = catalog?.sections?.length ? catalog.sections : DEFAULT_SECTIONS; const articles = data?.data || []; const visibleArticles = articles.filter((article) => article.subcategory === section);
  const save = async (payload) => { setFormError(''); try { if (editing) await updateMutation.mutateAsync({ id: editing._id, payload }); else await createMutation.mutateAsync(payload); setFormOpen(false); } catch (requestError) { setFormError(errorMessage(requestError, t('saveGuideError'))); } };
  const toggleStatus = async (article) => { try { await updateMutation.mutateAsync({ id: article._id, payload: { status: article.status === 'published' ? 'draft' : 'published' } }); } catch (requestError) { setFormError(errorMessage(requestError, t('guidePublicationError'))); } };
  const remove = async () => { try { await deleteMutation.mutateAsync(deleting._id); setDeleting(null); } catch (requestError) { setFormError(errorMessage(requestError, t('deleteGuideError'))); } };
  return <AppShell><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 mb-6"><div><p className="text-sm text-gray-500">{t('dashboard')} / {t('gettingStarted')}</p><h1 className="text-2xl font-bold text-gray-800 mt-1">{t('gettingStartedTitle')}</h1><p className="text-gray-500 mt-1">{t('gettingStartedSubtitle')}</p></div>{canManage && <button type="button" onClick={() => { setEditing(null); setFormError(''); setFormOpen(true); }} className="bg-primary-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-primary-700 shrink-0">{t('addGuide')}</button>}</div><div className="flex flex-col sm:flex-row gap-3 mb-5"><div className="flex flex-wrap gap-2" role="tablist" aria-label={t('gettingStarted')}>{sections.map((item) => <button key={item} type="button" role="tab" aria-selected={section === item} onClick={() => setSection(item)} className={`px-4 py-2 rounded-full text-sm font-medium ${section === item ? 'bg-primary-600 text-white' : 'bg-white border border-gray-200 text-gray-600 hover:border-primary-300'}`}>{label(item)}</button>)}</div>{canManage && <select value={status} onChange={(event) => setStatus(event.target.value)} className="sm:ml-auto px-3 py-2 border border-gray-300 rounded-md bg-white text-sm"><option value="">{t('allStatuses')}</option><option value="published">{t('published')}</option><option value="draft">{t('draft')}</option><option value="archived">{t('archived')}</option></select>}</div>{formError && <p className="mb-4 text-sm text-red-700 bg-red-50 border border-red-200 rounded-md px-3 py-2">{formError}</p>}{isLoading && <div className="rounded-lg border border-gray-200 bg-white p-10 text-center text-gray-500">{t('loadingGuide')}</div>}{isError && <div className="rounded-lg border border-red-200 bg-red-50 p-6 text-center text-red-700">{errorMessage(error, t('unableLoad'))}</div>}{!isLoading && !isError && visibleArticles.length === 0 && <div className="rounded-xl border border-gray-200 bg-white p-10 text-center text-gray-500">{t('noSectionArticles')}</div>}{!isLoading && !isError && visibleArticles.length > 0 && <div className="space-y-4">{visibleArticles.map((article) => <ArticleCard key={article._id} article={article} canManage={canManage} onEdit={(item) => { setEditing(item); setFormError(''); setFormOpen(true); }} onToggle={toggleStatus} onDelete={setDeleting} />)}</div>}<Modal open={formOpen} onClose={() => setFormOpen(false)} title={editing ? t('editGuide') : t('createGuide')} size="lg"><ArticleForm initial={editing} sections={sections} roles={catalog?.roles || []} onSubmit={save} onCancel={() => setFormOpen(false)} submitting={createMutation.isPending || updateMutation.isPending} formError={formError} /></Modal><ConfirmDialog open={!!deleting} onClose={() => setDeleting(null)} onConfirm={remove} title={t('deleteGuide')} message={deleting ? t('deleteConfirm', { name: deleting.title }) : ''} confirmLabel={t('delete')} loading={deleteMutation.isPending} /></AppShell>;
}

function ArticleCard({ article, canManage, onEdit, onToggle, onDelete }) { const { t } = useLanguage(); const [imageFailed, setImageFailed] = useState(false); return <article className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm">{article.coverImage && !imageFailed ? <img src={article.coverImage} alt="" onError={() => setImageFailed(true)} className="w-full h-56 sm:h-64 object-cover" /> : <div className="h-3 bg-gradient-to-r from-primary-500 to-cyan-400" />}<div className="p-5"><div className="flex flex-col sm:flex-row sm:items-start gap-3 justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-gray-800">{article.title}</h2>{canManage && <ContentBadge value={article.status} />}</div>{article.summary && <p className="text-gray-600 mt-2">{article.summary}</p>}</div>{canManage && <div className="flex gap-3 text-sm shrink-0"><button type="button" onClick={() => onEdit(article)} className="text-primary-600 hover:underline">{t('edit')}</button><button type="button" onClick={() => onToggle(article)} className="text-amber-700 hover:underline">{article.status === 'published' ? t('unpublish') : t('publish')}</button><button type="button" onClick={() => onDelete(article)} className="text-red-600 hover:underline">{t('delete')}</button></div>}</div><details className="mt-4 border-t border-gray-100 pt-3"><summary className="cursor-pointer text-sm font-medium text-primary-700">{t('readGuide')}</summary><div className="mt-3"><RichTextRenderer content={article.content} /></div></details>{article.tags?.length > 0 && <div className="flex flex-wrap gap-1 mt-4">{article.tags.map((tag) => <span key={tag} className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-500">#{tag}</span>)}</div>}</div></article>; }

function ArticleForm({ initial, sections, roles, onSubmit, onCancel, submitting, formError }) { const { t, label } = useLanguage(); const [form, setForm] = useState(() => toForm(initial, sections)); useEffect(() => setForm(toForm(initial, sections)), [initial, sections]); const set = (field, value) => setForm((current) => ({ ...current, [field]: value })); const toggleRole = (role) => set('targetRoles', form.targetRoles.includes(role) ? form.targetRoles.filter((item) => item !== role) : [...form.targetRoles, role]); const submit = (event) => { event.preventDefault(); onSubmit({ ...form, category: 'getting_started', tags: form.tags.split(',').map((tag) => tag.trim()).filter(Boolean), sortOrder: Number(form.sortOrder), targetRoles: form.targetRoles }); }; return <form onSubmit={submit} className="space-y-4">{formError && <p className="text-sm text-red-600">{formError}</p>}<Field label={t('title')} value={form.title} onChange={(value) => set('title', value)} required /><div className="grid gap-4 sm:grid-cols-2"><Field label={t('slug')} value={form.slug} onChange={(value) => set('slug', value)} required /><SelectField label={t('section')} value={form.subcategory} onChange={(value) => set('subcategory', value)} options={sections} /></div><Field label={t('summary')} value={form.summary} onChange={(value) => set('summary', value)} /><RichTextEditor label={t('guideContent')} value={form.content} onChange={(value) => set('content', value)} /><Field label={t('coverImageUrl')} value={form.coverImage} onChange={(value) => set('coverImage', value)} /><div className="grid gap-4 sm:grid-cols-2"><Field label={t('tags')} value={form.tags} onChange={(value) => set('tags', value)} /><Field label={t('sortOrder')} type="number" value={form.sortOrder} onChange={(value) => set('sortOrder', value)} /></div><SelectField label={t('status')} value={form.status} onChange={(value) => set('status', value)} options={['draft', 'published', 'archived']} /><div><span className="block text-sm font-medium text-gray-700 mb-2">{t('targetRoles')}</span><div className="flex flex-wrap gap-3">{roles.map((role) => <label key={role} className="text-sm text-gray-600"><input type="checkbox" checked={form.targetRoles.includes(role)} onChange={() => toggleRole(role)} className="mr-1" />{label(role)}</label>)}</div></div><div className="flex justify-end gap-3 pt-2"><button type="button" onClick={onCancel} className="px-4 py-2 text-sm rounded-md border border-gray-300 hover:bg-gray-50">{t('cancel')}</button><button type="submit" disabled={submitting} className="px-4 py-2 text-sm rounded-md bg-primary-600 text-white font-medium hover:bg-primary-700 disabled:opacity-50">{submitting ? t('saving') : t('saveArticle')}</button></div></form>; }
function toForm(article, sections) { return article ? { ...EMPTY_ARTICLE, ...article, subcategory: article.subcategory || sections[0], tags: (article.tags || []).join(', '), targetRoles: article.targetRoles || [] } : { ...EMPTY_ARTICLE, subcategory: sections[0] }; }
function Field({ label: fieldLabel, value, onChange, type = 'text', required = false }) { return <label className="block"><span className="block text-sm font-medium text-gray-700 mb-1">{fieldLabel}{required && ' *'}</span><input type={type} value={value ?? ''} onChange={(event) => onChange(event.target.value)} required={required} className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-primary-500 focus:ring-2 focus:ring-primary-100 outline-none" /></label>; }
function SelectField({ label: fieldLabel, value, onChange, options }) { const { label } = useLanguage(); return <label className="block"><span className="block text-sm font-medium text-gray-700 mb-1">{fieldLabel}</span><select value={value ?? ''} onChange={(event) => onChange(event.target.value)} className="w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm">{options.map((option) => <option key={option} value={option}>{label(option)}</option>)}</select></label>; }
