import { Link, useParams } from 'react-router-dom';
import { useIntern } from '../hooks/useInterns.js';
import StatusBadge from '../components/interns/StatusBadge.jsx';
import { ImageWithFallback } from '../components/common/ImageUpload.jsx';

export default function InternDetail() {
  const { id } = useParams();
  const { data: intern, isLoading, isError, error } = useIntern(id);
  if (isLoading) return <Shell><p className="py-12 text-center text-gray-500">Loading intern...</p></Shell>;
  if (isError) return <Shell><p className="py-12 text-center text-red-600">{error?.response?.data?.message || 'Unable to load intern.'}</p></Shell>;
  if (!intern) return null;
  return <Shell><p className="text-sm text-gray-500"><Link to="/interns" className="hover:underline">Intern Directory</Link> / Detail</p><div className="flex flex-col sm:flex-row gap-5 items-start mt-3 mb-6"><ImageWithFallback src={intern.profileImage} alt={`${intern.firstName} ${intern.lastName}`} className="w-28 h-28 rounded-lg object-cover" fallback={`${intern.firstName?.[0] || ''}${intern.lastName?.[0] || ''}`} /><div><h1 className="text-2xl font-bold text-gray-800">{intern.firstName} {intern.lastName}</h1><p className="text-gray-500">{intern.nickname ? `${intern.nickname} · ` : ''}{intern.university}</p><div className="flex gap-2 mt-2"><StatusBadge status={intern.status} />{intern.departmentId && <span className="px-2 py-0.5 rounded text-xs bg-gray-100 text-gray-600">{intern.departmentId.name}</span>}</div></div></div><div className="grid gap-4 sm:grid-cols-3 mb-6"><Info label="Batch" value={intern.batchId ? <Link to={`/intern-batches/${intern.batchId._id}`} className="text-primary-600 hover:underline">{intern.batchId.code} — {intern.batchId.title}</Link> : '—'} /><Info label="Mentor" value={intern.mentorId ? `${intern.mentorId.firstName} ${intern.mentorId.lastName}` : 'Not assigned'} /><Info label="Dates" value={`${new Date(intern.startDate).toLocaleDateString()} – ${new Date(intern.endDate).toLocaleDateString()}`} /><Info label="Faculty / major" value={`${intern.faculty || '—'} / ${intern.major || '—'}`} /><Info label="Study year" value={intern.year || '—'} /><Info label="Duration" value={intern.durationDays ? `${intern.durationDays} days` : '—'} /></div><section className="bg-white border border-gray-200 rounded-lg p-4"><h2 className="font-semibold text-gray-800 mb-2">Profile</h2><p className="text-gray-600">{intern.shortBio || 'No short bio provided.'}</p>{intern.projectTitle && <p className="mt-3 text-sm"><span className="font-medium">Project:</span> {intern.projectTitle}</p>}{intern.privacyConsent && (intern.lessonsLearned || intern.adviceForNextBatch) && <div className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Lessons learned" value={intern.lessonsLearned || '—'} /><Info label="Advice for next batch" value={intern.adviceForNextBatch || '—'} /></div>}</section></Shell>;
}
function Shell({ children }) { return <div className="min-h-screen bg-gray-50"><header className="bg-white border-b border-gray-200"><div className="max-w-5xl mx-auto px-4 py-4 flex items-center justify-between"><h1 className="text-xl font-bold text-primary-600">FTI Welcome Hub</h1><Link to="/dashboard" className="text-sm text-gray-500 hover:text-gray-700">← Dashboard</Link></div></header><main className="max-w-5xl mx-auto px-4 py-6">{children}</main></div>; }
function Info({ label, value }) { return <div className="bg-white border border-gray-200 rounded-lg p-4"><p className="text-xs uppercase tracking-wide text-gray-400">{label}</p><p className="text-gray-700 mt-1">{value}</p></div>; }
